<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllOrdered()
    {
        $qb = $this->createQueryBuilder('cat')
            ->addOrderBy('cat.name', 'ASC');

        $this->addFortuneCookieJoinAndSelect($qb);

        $query = $qb->getQuery();

        return $query->execute();
        //dump($query->getSQL());
        //die;
    }
    
    public function search($term)
    {
        $qb = $this->createQueryBuilder('cat')
            ->andWhere('cat.name LIKE :searchTerm 
                OR cat.iconKey LIKE :searchTerm 
                OR fc.fortune LIKE :searchTerm')
            ->setParameter('searchTerm', '%'.$term.'%');

        $this->addFortuneCookieJoinAndSelect($qb);

        return $qb->getQuery()
                  ->execute();
    }
    
    public function findWithFortunesJoin($id)
    {
        $qb = $this->createQueryBuilder('cat')
            ->andWhere('cat.id = :id')
            ->setParameter('id', $id);

        $this->addFortuneCookieJoinAndSelect($qb);

        return $qb->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param QueryBuilder $qb
     * @return QueryBuilder
     */
    private function addFortuneCookieJoinAndSelect(QueryBuilder $qb)
    {
        return $qb->leftJoin('cat.fortuneCookies', 'fc')
                  ->addSelect('fc');
    }
}
